version: "3"

services:
  
  nginx:
    image: nginx:latest
    container_name: progetto_reti
    volumes:
      - /backend/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/www/data/static
      - ./certs:/etc/nginx/certs
    links:
      - node1:node1
    depends_on:
      - node1
    ports:
      - "3000:80"
      - "3003:443"
    networks:
      - app-network
    
  node1:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - app-network

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB='RDC'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'

networks:
  app-network:
    driver: bridge
    